# Generated by Django 5.0.3 on 2024-03-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppilerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_mobileno', models.IntegerField(blank=True, null=True)),
                ('supplier_email', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
