# Generated by Django 5.0.3 on 2024-03-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppilerdb',
            old_name='supplier_address',
            new_name='s_address',
        ),
        migrations.RenameField(
            model_name='suppilerdb',
            old_name='supplier_email',
            new_name='s_email',
        ),
        migrations.RenameField(
            model_name='suppilerdb',
            old_name='supplier_mobileno',
            new_name='s_mobileno',
        ),
        migrations.RenameField(
            model_name='suppilerdb',
            old_name='supplier_name',
            new_name='s_name',
        ),
    ]
