# Generated by Django 5.0.3 on 2024-04-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0003_stocksdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchasesdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliername', models.CharField(blank=True, max_length=100, null=True)),
                ('suppliermobileno', models.IntegerField(blank=True, null=True)),
                ('stockname', models.CharField(blank=True, max_length=100, null=True)),
                ('stockprice', models.IntegerField(blank=True, null=True)),
                ('stockquantity', models.IntegerField(blank=True, null=True)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
