# Generated by Django 5.0.3 on 2024-04-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0005_suppilerdb_s_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesdb',
            name='suppliergstin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
