# Generated by Django 5.0.3 on 2024-04-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0006_purchasesdb_suppliergstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesdb',
            name='stockname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventoryapp.stocksdb'),
        ),
    ]
