# Generated by Django 5.0.3 on 2024-04-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0008_alter_purchasesdb_stockname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesdb',
            name='stockprice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasesdb',
            name='stockquantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
