# Generated by Django 5.0.3 on 2024-04-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0009_alter_purchasesdb_stockprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasesdb',
            name='stockname',
        ),
        migrations.AddField(
            model_name='purchasesdb',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventoryapp.stocksdb'),
        ),
    ]
