# Generated by Django 5.0.3 on 2024-04-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0011_purchase_delete_purchasesdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='sgtockquantity',
            new_name='stockquantity',
        ),
        migrations.AlterField(
            model_name='stocksdb',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
