# Generated by Django 5.0.3 on 2024-04-07 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0013_purchasesdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=100, null=True)),
                ('cmobileno', models.IntegerField(blank=True, null=True)),
                ('cemail', models.CharField(blank=True, max_length=100, null=True)),
                ('caddress', models.CharField(blank=True, max_length=100, null=True)),
                ('cgstin', models.CharField(max_length=100, null=True)),
                ('stockprice', models.PositiveIntegerField(blank=True, null=True)),
                ('stockquantity', models.PositiveIntegerField(blank=True, null=True)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventoryapp.stocksdb')),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
